Use "4_MyBase"
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPENAME.AUDITORIUM_TYPENAME
FROM AUDITORIUM AUDITORIUM
INNER JOIN AUDITORIUM_TYPE AUDITORIUM_TYPENAME 
ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPENAME.AUDITORIUM_TYPE;