USE [4_MyBase]
SELECT      
f.FACULTY_NAME AS 'Факультет',     
p.PROFESSION_NAME AS 'Специальность',     
s.SUBJECT_NAME AS 'Дисциплина',    
AVG(pr.NOTE) AS 'Средняя оценка' 
FROM      
FACULTY f     
JOIN PROFESSION p ON f.FACULTY = p.FACULTY     
JOIN GROUPS g ON p.PROFESSION = g.PROFESSION    
JOIN STUDENT st ON g.IDGROUP = st.IDGROUP    
JOIN PROGRESS pr ON st.IDSTUDENT = pr.IDSTUDENT    
JOIN SUBJECT s ON pr.SUBJECT = s.SUBJECT 
WHERE     
f.FACULTY = 'TOV' 
GROUP BY      
ROLLUP(f.FACULTY_NAME, p.PROFESSION_NAME, s.SUBJECT_NAME) 
ORDER BY      f.FACULTY_NAME, p.PROFESSION_NAME, s.SUBJECT_NAME;