USE [4_MyBase]
SELECT 
    'TOV' AS FACULTY,
    p.PROFESSION_NAME AS PROFESSION,
    s.SUBJECT_NAME AS SUBJECT,
    AVG(pr.NOTE) AS AVG_NOTE
FROM 
    FACULTY f
    JOIN PROFESSION p ON f.FACULTY = p.FACULTY
    JOIN GROUPS g ON p.PROFESSION = g.PROFESSION
    JOIN STUDENT st ON g.IDGROUP = st.IDGROUP
    JOIN PROGRESS pr ON st.IDSTUDENT = pr.IDSTUDENT
    JOIN SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE 
    f.FACULTY = 'TOV'
GROUP BY 
    p.PROFESSION_NAME, s.SUBJECT_NAME

INTERSECT

SELECT 
    'HTT' AS FACULTY,
    p.PROFESSION_NAME AS PROFESSION,
    s.SUBJECT_NAME AS SUBJECT,
    AVG(pr.NOTE) AS AVG_NOTE
FROM 
    FACULTY f
    JOIN PROFESSION p ON f.FACULTY = p.FACULTY
    JOIN GROUPS g ON p.PROFESSION = g.PROFESSION
    JOIN STUDENT st ON g.IDGROUP = st.IDGROUP
    JOIN PROGRESS pr ON st.IDSTUDENT = pr.IDSTUDENT
    JOIN SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE 
    f.FACULTY = 'HTT'
GROUP BY 
    p.PROFESSION_NAME, s.SUBJECT_NAME;