USE "4_MyBase"
SELECT 
    AT.AUDITORIUM_TYPENAME, 
    MAX(A.AUDITORIUM_CAPACITY) AS MAX_CAPACITY,
    MIN(A.AUDITORIUM_CAPACITY) AS MIN_CAPACITY,
    AVG(A.AUDITORIUM_CAPACITY) AS AVG_CAPACITY,
    SUM(A.AUDITORIUM_CAPACITY) AS TOTAL_CAPACITY,
    COUNT(A.AUDITORIUM) AS AUDITORIUM_COUNT
FROM 
    AUDITORIUM A
INNER JOIN 
    AUDITORIUM_TYPE AT ON A.AUDITORIUM_TYPE = AT.AUDITORIUM_TYPE
GROUP BY 
    AT.AUDITORIUM_TYPENAME;