USE "4_MyBase"
SELECT 
    F.FACULTY_NAME, 
    G.PROFESSION AS GROUP_NAME, 
    ROUND(AVG(P.NOTE), 2) AS AVG_GRADE 
FROM 
    FACULTY F
INNER JOIN 
    GROUPS G ON F.FACULTY = G.FACULTY  
INNER JOIN 
    STUDENT S ON G.IDGROUP = S.IDGROUP
INNER JOIN 
    PROGRESS P ON S.IDSTUDENT = P.IDSTUDENT
GROUP BY 
    F.FACULTY_NAME, G.PROFESSION  
ORDER BY 
    AVG_GRADE DESC;