USE "4_MyBase"
SELECT 
    F.FACULTY_NAME,
    G.IDGROUP,
    AVG(P.NOTE) AS AVG_GRADE
FROM 
    FACULTY F
INNER JOIN 
    GROUPS G ON F.FACULTY = G.FACULTY  
INNER JOIN 
    STUDENT S ON G.IDGROUP = S.IDGROUP  
INNER JOIN 
    PROGRESS P ON S.IDSTUDENT = P.IDSTUDENT  
INNER JOIN 
    [SUBJECT] SUB ON P.[SUBJECT] = SUB.[SUBJECT]  
WHERE 
    P.[SUBJECT] IN ('DB', 'OAP')  
GROUP BY 
    F.FACULTY_NAME, G.IDGROUP
ORDER BY 
    AVG_GRADE DESC;