USE "4_MyBase"
SELECT 
    F.FACULTY,
    PR.PROFESSION_NAME AS SPECIALTY_NAME,
    SUB.SUBJECT_NAME AS DISCIPLINE_NAME,
    AVG(P.NOTE) AS AVG_GRADE
FROM 
    FACULTY F
LEFT JOIN 
    GROUPS G ON F.FACULTY = G.FACULTY
LEFT JOIN 
    STUDENT ST ON G.IDGROUP = ST.IDGROUP
LEFT JOIN 
    PROGRESS P ON ST.IDSTUDENT = P.IDSTUDENT
LEFT JOIN 
    PROFESSION PR ON G.PROFESSION = PR.PROFESSION
LEFT JOIN 
    [SUBJECT] SUB ON P.[SUBJECT] = SUB.[SUBJECT]
WHERE 
    F.FACULTY = 'TOV'
GROUP BY 
    F.FACULTY, PR.PROFESSION_NAME, SUB.SUBJECT_NAME
ORDER BY 
    AVG_GRADE DESC;