SELECT 
    SUB.SUBJECT_NAME AS DISCIPLINE_NAME,  
    COUNT(*) AS STUDENT_COUNT
FROM 
    PROGRESS P
INNER JOIN 
    SUBJECT SUB ON P.SUBJECT = SUB.SUBJECT  
WHERE 
    P.NOTE IN (8, 9) 
GROUP BY 
    SUB.SUBJECT_NAME
HAVING 
    COUNT(*) > 0
ORDER BY 
    SUB.SUBJECT_NAME;