USE [4_MyBase];

SELECT * FROM sys.indexes;

EXEC SP_HELPINDEX 'AUDITORIUM';
EXEC SP_HELPINDEX 'AUDITORIUM_TYPE';
EXEC SP_HELPINDEX 'FACULTY';
EXEC SP_HELPINDEX 'GROUPS';
EXEC SP_HELPINDEX 'PROFESSION';
EXEC SP_HELPINDEX 'PULPIT';
EXEC SP_HELPINDEX 'PROGRESS';
EXEC SP_HELPINDEX 'STUDENT';
EXEC SP_HELPINDEX 'SUBJECT';
EXEC SP_HELPINDEX 'TEACHER';
IF OBJECT_ID('tempdb..#EXPLRE') IS NOT NULL
DROP TABLE IF EXISTS #EXPLRE;

CREATE TABLE #EXPLRE
(
  TIND INT,
  TFIELD VARCHAR(100)
);

DECLARE @i INT = 0;
WHILE @i < 2000
BEGIN
  INSERT INTO #EXPLRE (TIND, TFIELD)
  VALUES (FLOOR(30000 * RAND()), REPLICATE('string', 10));
  
  SET @i = @i + 1;
END;

SELECT * 
FROM #EXPLRE 
WHERE TIND BETWEEN 1500 AND 2500 
ORDER BY TIND;

CHECKPOINT;
DBCC DROPCLEANBUFFERS;

CREATE CLUSTERED INDEX #EXPLRE_CL ON #EXPLRE (TIND ASC);
