USE [4_MyBase]
IF OBJECT_ID('tempdb..#EXPLRE') IS NOT NULL
    DROP TABLE #EXPLRE;


CREATE TABLE #EX
(
  TKEY INT,
  CC INT IDENTITY(1,1),
  TF VARCHAR(100)
);

DECLARE @I INT = 0;
WHILE @I < 20000
BEGIN
  INSERT INTO #EX (TKEY, TF)
  VALUES (FLOOR(30000 * RAND()), REPLICATE('string', 10));

  SET @I = @I + 1;
END;

SELECT COUNT(*) AS [COUNT OF STRING] FROM #EX;

SELECT * FROM #EX;

CREATE INDEX #EX_NONCLU ON #EX (TKEY, CC);

SELECT * FROM #EX WHERE TKEY > 1500 AND CC < 4500;

SELECT * FROM #EX ORDER BY TKEY, CC;

SELECT * FROM #EX WHERE TKEY = 556 AND CC > 3;

