USE [4_MyBase]
DROP TABLE IF EXISTS #EX;

CREATE TABLE #EX
(
  TKEY INT,
  CC INT IDENTITY(1,1), 
  TF VARCHAR(100)
);

SET NOCOUNT ON;

DECLARE @I INT = 0;
WHILE @I < 20000
BEGIN
  INSERT INTO #EX (TKEY, TF)  
  VALUES (FLOOR(30000 * RAND()), REPLICATE('string', 10));

  SET @I = @I + 1;
END;

CREATE INDEX #EX_TKEY_X ON #EX (TKEY) INCLUDE (CC);


SELECT CC FROM #EX WHERE TKEY > 15000;
