USE [4_MyBase];

IF OBJECT_ID('tempdb..#EX') IS NOT NULL
    DROP TABLE #EX;

CREATE TABLE #EX (
    TKEY INT,
    CC INT IDENTITY(1,1),
    TF VARCHAR(100)
);

SET NOCOUNT ON;

DECLARE @I INT = 0;
WHILE @I < 20000
BEGIN
    INSERT INTO #EX (TKEY, TF)
    VALUES (FLOOR(30000 * RAND()), REPLICATE('STRING', 10));
    SET @I = @I + 1;
END;

CREATE INDEX #EX_TKEY ON #EX(TKEY);

INSERT TOP (10000) INTO #EX(TKEY, TF)
SELECT TKEY, TF FROM #EX;

DECLARE @OBJID INT;
SELECT @OBJID = OBJECT_ID FROM tempdb.SYS.TABLES WHERE NAME LIKE '#EX%';

PRINT 'Ôðàãìåíòàöèÿ äî REORGANIZE:';
SELECT NAME AS [ÈÍÄÅÊÑ], AVG_FRAGMENTATION_IN_PERCENT AS [ÔÐÀÃÌÅÍÒÀÖÈß (%)]
FROM SYS.DM_DB_INDEX_PHYSICAL_STATS(DB_ID(N'tempdb'), @OBJID, NULL, NULL, NULL) SS
JOIN tempdb.SYS.INDEXES II 
    ON SS.OBJECT_ID = II.OBJECT_ID AND SS.INDEX_ID = II.INDEX_ID
WHERE NAME IS NOT NULL;

ALTER INDEX #EX_TKEY ON #EX REORGANIZE;

PRINT 'Ôðàãìåíòàöèÿ ïîñëå REORGANIZE:';
SELECT NAME AS [ÈÍÄÅÊÑ], AVG_FRAGMENTATION_IN_PERCENT AS [ÔÐÀÃÌÅÍÒÀÖÈß (%)]
FROM SYS.DM_DB_INDEX_PHYSICAL_STATS(DB_ID(N'tempdb'), @OBJID, NULL, NULL, NULL) SS
JOIN tempdb.SYS.INDEXES II 
    ON SS.OBJECT_ID = II.OBJECT_ID AND SS.INDEX_ID = II.INDEX_ID
WHERE NAME IS NOT NULL;

ALTER INDEX #EX_TKEY ON #EX REBUILD WITH (ONLINE = OFF);

PRINT 'Ôðàãìåíòàöèÿ ïîñëå REBUILD:';
SELECT NAME AS [ÈÍÄÅÊÑ], AVG_FRAGMENTATION_IN_PERCENT AS [ÔÐÀÃÌÅÍÒÀÖÈß (%)]
FROM SYS.DM_DB_INDEX_PHYSICAL_STATS(DB_ID(N'tempdb'), @OBJID, NULL, NULL, NULL) SS
JOIN tempdb.SYS.INDEXES II 
    ON SS.OBJECT_ID = II.OBJECT_ID AND SS.INDEX_ID = II.INDEX_ID
WHERE NAME IS NOT NULL;

DROP INDEX #EX_TKEY ON #EX;

CREATE INDEX #EX_TKEY ON #EX(TKEY)
WITH (FILLFACTOR = 65);

INSERT TOP (50) PERCENT INTO #EX(TKEY, TF)
SELECT TKEY, TF FROM #EX;

PRINT 'Ôðàãìåíòàöèÿ ïîñëå âñòàâêè ñ fillfactor = 65:';
SELECT NAME AS [ÈÍÄÅÊÑ], AVG_FRAGMENTATION_IN_PERCENT AS [ÔÐÀÃÌÅÍÒÀÖÈß (%)]
FROM SYS.DM_DB_INDEX_PHYSICAL_STATS(DB_ID(N'tempdb'), @OBJID, NULL, NULL, NULL) SS
JOIN tempdb.SYS.INDEXES II 
    ON SS.OBJECT_ID = II.OBJECT_ID AND SS.INDEX_ID = II.INDEX_ID
WHERE NAME IS NOT NULL;
