ALTER VIEW Количество_кафедр WITH SCHEMABINDING AS
SELECT 
    f.FACULTY_NAME AS Факультет, 
    COUNT(p.PULPIT) AS Количество_кафедр
FROM dbo.FACULTY f
LEFT JOIN dbo.PULPIT p ON f.FACULTY = p.FACULTY
GROUP BY f.FACULTY_NAME;