USE "4_MyBase"
SELECT DISTINCT PULPIT.PULPIT_NAME
FROM PULPIT
INNER JOIN (
    SELECT DISTINCT FACULTY
    FROM PROFESSION
    WHERE PROFESSION.PROFESSION_NAME LIKE '%Technology%'
) AS PROF_FAC ON PULPIT.FACULTY = PROF_FAC.FACULTY;