USE "4_MyBase"
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM.AUDITORIUM_NAME, AUDITORIUM.AUDITORIUM_TYPE, AUDITORIUM.AUDITORIUM_CAPACITY
FROM AUDITORIUM 
WHERE AUDITORIUM.AUDITORIUM_CAPACITY = (
    SELECT TOP 1 A2.AUDITORIUM_CAPACITY
    FROM AUDITORIUM A2
    WHERE A2.AUDITORIUM_TYPE = AUDITORIUM.AUDITORIUM_TYPE
    ORDER BY A2.AUDITORIUM_CAPACITY DESC
)
ORDER BY AUDITORIUM.AUDITORIUM_CAPACITY DESC;
