
USE "4_MyBase"
INSERT INTO FACULTY (FACULTY, FACULTY_NAME)
VALUES ('TEST_FAC', 'Тестовый факультет');
SELECT F.FACULTY_NAME
FROM FACULTY F
WHERE NOT EXISTS (
    SELECT 1
    FROM PULPIT P
    WHERE P.FACULTY = F.FACULTY
);
